### ISSUE TITLE
Multi-Line Comments In prepGFG.py

### ISSUE THREAD

**Issue by dspsolves** [dsp9107/EssentialTools#1]
`prepGFG.py` Does Not **Remove Multi-Line Comments**, Efficiently . Starting Line And Ending Line Are Removed .

**Comment by adinalini** [comment]
What do we have to do exactly? I am interested.

**Comment by dspsolves** [comment]
Whenever One Copies C++ Code From [GeeksForGeeks](https://www.geeksforgeeks.org) , There Are Comments And Trailing Whitespaces . I Removed The Whitespaces And Single-Line Comments . It's Also Removing The Starting of A Multi-Line Comment . You Need To Remove The Whole Multi-Line Comment .

**Comment by pcube99** [comment]
I would love to claim this.

**Comment by dspsolves** [comment]
Go Ahead 👍

**Comment by dspsolves** [comment]
@pcube99 Fixed The Issue . ⭐️ 
Others Are Most Welcome To Suggest Improvements . 🕊
